# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('ui_sref', models.CharField(max_length=255, verbose_name='ui sref')),
                ('icon', models.CharField(max_length=255, verbose_name='icon')),
                ('lft', models.PositiveIntegerField(db_index=True, editable=False)),
                ('rght', models.PositiveIntegerField(db_index=True, editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(db_index=True, editable=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menu_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_menu_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.Menu')),
            ],
            options={
                'verbose_name': 'menu',
                'permissions': (('list_menu', 'can list menu'), ('detail_menu', 'can detail menu'), ('disable_menu', 'can disable menu')),
                'verbose_name_plural': 'menus',
            },
        ),
    ]
