# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 15:55
from __future__ import unicode_literals

import apps.quotation.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
        ('profile', '0013_remove_invitation_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('date_bom', models.DateField(verbose_name='date')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='material_bills', to='profile.Profile', verbose_name='contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_bom_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_bom_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='profile.Company', verbose_name='customer')),
                ('selected_companies', models.ManyToManyField(blank=True, related_name='selected_boms', to='profile.Company', verbose_name='selected companies')),
            ],
            options={
                'verbose_name': 'bom',
                'verbose_name_plural': 'boms',
                'permissions': (('list_bom', 'can list bom'), ('detail_bom', 'can detail bom'), ('disable_bom', 'can disable bom')),
            },
        ),
        migrations.CreateModel(
            name='BomRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='quantity')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bom_rows', to='quotation.Bom', verbose_name='material bill')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_rows', to='product.Category', verbose_name='category')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_bomrow_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_bomrow_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_rows', to='product.Product', verbose_name='product')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_rows', to='product.Subcategory', verbose_name='subcategory')),
                ('typology', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_rows', to='product.Typology', verbose_name='typology')),
                ('unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bom_rows', to='product.Unit', verbose_name='measurement unit')),
            ],
            options={
                'verbose_name': 'bom row',
                'verbose_name_plural': 'bom rows',
                'permissions': (('list_bomrow', 'can list bom row'), ('detail_bomrow', 'can detail bom row'), ('disable_bomrow', 'can disable bom row')),
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('document', models.FileField(upload_to=apps.quotation.models.get_upload_certification_path, verbose_name='certification')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_certification_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_certification_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profile.Company', verbose_name='owner')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'permissions': (('list_certification', 'can list certification'), ('detail_certification', 'can detail certification'), ('disable_certification', 'can disable certification')),
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='publication date')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='price')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None)),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='profile.Profile', verbose_name='contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_offer_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_offer_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='profile.Company', verbose_name='customer')),
            ],
            options={
                'verbose_name': 'offer',
                'verbose_name_plural': 'offers',
                'permissions': (('list_offer', 'can list offer'), ('detail_offer', 'can detail offer'), ('disable_offer', 'can disable offer')),
            },
        ),
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('date_quotation', models.DateField(verbose_name='date')),
                ('deadline', models.DateField(verbose_name='deadline')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='quotation.Bom', verbose_name='material bill')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='profile.Profile', verbose_name='contact')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotation_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotation_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotations', to='profile.Company', verbose_name='company')),
            ],
            options={
                'verbose_name': 'quotation',
                'verbose_name_plural': 'quotations',
                'permissions': (('list_quotation', 'can list quotation'), ('detail_quotation', 'can detail quotation'), ('disable_quotation', 'can disable quotation')),
            },
        ),
        migrations.CreateModel(
            name='QuotationRow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='price')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='quantity')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='name')),
                ('description', models.TextField(blank=True, null=True, verbose_name='description')),
                ('note', models.TextField(blank=True, null=True, verbose_name='note')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='total')),
                ('is_accepted', models.BooleanField(default=False, verbose_name='is accepted')),
                ('is_completed', models.BooleanField(default=False, verbose_name='is completed')),
                ('is_viewed', models.BooleanField(default=False, verbose_name='is viewed')),
                ('is_confirmed', models.BooleanField(default=False, verbose_name='is confirmed')),
                ('is_paid', models.BooleanField(default=False, verbose_name='is paid')),
                ('bom_row', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_rows', to='quotation.BomRow', verbose_name='material bill row')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationrow_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationrow_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_rows', to='quotation.Quotation', verbose_name='quotation')),
            ],
            options={
                'verbose_name': 'quotation row',
                'verbose_name_plural': 'quotation rows',
                'permissions': (('list_quotationrow', 'can list quotation row'), ('detail_quotationrow', 'can detail quotation row'), ('disable_quotationrow', 'can disable quotation row')),
            },
        ),
    ]
