# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 07:05
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0002_auto_20170721_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_bills', to='profile.Profile', verbose_name='contact'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='profile.Company', verbose_name='owner'),
        ),
        migrations.AlterField(
            model_name='bom',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='quotation',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
    ]
