# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 08:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_delegateprofile_guestprofile_level1profile_level2profile_mainprofile_ownerprofile_phantomprofile'),
        ('quotation', '0003_auto_20170731_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='profile.Profile', verbose_name='contact'),
        ),
    ]
