# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20171103_1450'),
        ('quotation', '0004_certification_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='internal_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='project.InternalProject', verbose_name='internal project'),
        ),
    ]
