# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 15:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0005_bom_internal_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bom',
            name='internal_project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='project.InternalProject', verbose_name='internal project'),
        ),
    ]
