# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-06 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0006_auto_20171103_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bomrow',
            name='description',
            field=models.TextField(verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='bomrow',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name'),
        ),
    ]
