# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-20 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0007_auto_20171106_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='draft'),
        ),
    ]
