# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0008_bom_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bom',
            name='internal_project',
        ),
    ]
