# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-21 08:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_genericproject_internalsharedproject'),
        ('quotation', '0009_remove_bom_internal_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='bom',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='project.Project', verbose_name='project'),
        ),
    ]
