# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0010_bom_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='draft'),
        ),
    ]
