# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 13:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0011_quotation_is_draft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotationrow',
            name='is_accepted',
        ),
        migrations.RemoveField(
            model_name='quotationrow',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='quotationrow',
            name='is_confirmed',
        ),
        migrations.RemoveField(
            model_name='quotationrow',
            name='is_paid',
        ),
        migrations.RemoveField(
            model_name='quotationrow',
            name='is_viewed',
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_accepted',
            field=models.BooleanField(default=False, verbose_name='is accepted'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='is completed'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='is confirmed'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='is paid'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='is_viewed',
            field=models.BooleanField(default=False, verbose_name='is viewed'),
        ),
    ]
