# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 09:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0033_auto_20180103_1426'),
        ('quotation', '0012_auto_20171213_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavouriteOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_favouriteoffer_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_favouriteoffer_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_offers', to='quotation.Offer', verbose_name='offer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favourite_offers', to='profile.Profile', verbose_name='contact')),
            ],
            options={
                'verbose_name': 'favourite offer',
                'verbose_name_plural': 'favourite offers',
                'permissions': (('list_favouriteoffer', 'can list favourite offer'), ('detail_favouriteoffer', 'can detail favourite offer')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='favouriteoffer',
            unique_together=set([('profile', 'offer')]),
        ),
    ]
