# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_auto_20180103_1426'),
        ('quotation', '0013_auto_20180117_0908'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='followers',
            field=models.ManyToManyField(related_name='followings_offers', through='quotation.FavouriteOffer', to='profile.Profile', verbose_name='followers'),
        ),
    ]
