# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 14:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0014_offer_followers'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_draft',
            field=models.BooleanField(default=True, verbose_name='draft'),
        ),
    ]
