# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 15:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('quotation', '0015_offer_is_draft'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.Product', verbose_name='product'),
        ),
    ]
