# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 15:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0033_auto_20180103_1426'),
        ('quotation', '0016_offer_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_orderedoffer_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_orderedoffer_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_offers', to='quotation.Offer', verbose_name='offer')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_offers', to='profile.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name_plural': 'ordered offers',
                'permissions': (('list_orderedoffer', 'can list ordered offer'), ('detail_orderedoffer', 'can detail ordered offer')),
                'verbose_name': 'ordered offer',
            },
        ),
        migrations.AddField(
            model_name='offer',
            name='buyers',
            field=models.ManyToManyField(related_name='buying_offers', through='quotation.OrderedOffer', to='profile.Profile', verbose_name='buyers'),
        ),
        migrations.AlterUniqueTogether(
            name='orderedoffer',
            unique_together=set([('profile', 'offer')]),
        ),
    ]
