# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 16:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0033_auto_20180103_1426'),
        ('quotation', '0017_auto_20180117_1552'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoughtOffer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_boughtoffer_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_boughtoffer_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'verbose_name_plural': 'ordered offers',
                'verbose_name': 'ordered offer',
                'permissions': (('list_boughtoffer', 'can list bought offer'), ('detail_boughtoffer', 'can detail bought offer')),
            },
        ),
        migrations.AlterUniqueTogether(
            name='orderedoffer',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='orderedoffer',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='orderedoffer',
            name='last_modifier',
        ),
        migrations.RemoveField(
            model_name='orderedoffer',
            name='offer',
        ),
        migrations.RemoveField(
            model_name='orderedoffer',
            name='profile',
        ),
        migrations.AlterField(
            model_name='offer',
            name='buyers',
            field=models.ManyToManyField(related_name='buying_offers', through='quotation.BoughtOffer', to='profile.Profile', verbose_name='buyers'),
        ),
        migrations.DeleteModel(
            name='OrderedOffer',
        ),
        migrations.AddField(
            model_name='boughtoffer',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_offers', to='quotation.Offer', verbose_name='offer'),
        ),
        migrations.AddField(
            model_name='boughtoffer',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_offers', to='profile.Profile', verbose_name='profile'),
        ),
        migrations.AlterUniqueTogether(
            name='boughtoffer',
            unique_together=set([('profile', 'offer')]),
        ),
    ]
