# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 12:46
from __future__ import unicode_literals

import apps.quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0018_auto_20180117_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.quotation.models.get_upload_photo_path, verbose_name='image'),
        ),
    ]
