# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 14:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('quotation', '0019_offer_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='product.Unit', verbose_name='unit'),
        ),
    ]
