# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-21 14:55
from __future__ import unicode_literals

import apps.quotation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0020_offer_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='photo',
            field=models.ImageField(blank=True, upload_to=apps.quotation.models.get_upload_offer_path, verbose_name='image'),
        ),
    ]
