# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-22 13:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotation', '0021_auto_20180121_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='start_date',
            field=models.DateField(default=datetime.date(2018, 1, 22), verbose_name='start date'),
            preserve_default=False,
        ),
    ]
