# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-11-06 11:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0044_sponsor_expired_date'),
        ('quotation', '0023_auto_20180130_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='BomArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('bom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_boms', to='quotation.Bom', verbose_name='bom')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_boms', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_bomarchive_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_bomarchive_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'verbose_name_plural': 'bom archives',
                'verbose_name': 'bom archive',
                'permissions': (('list_bomarchive', 'can list bom archive'), ('detail_bomarchive', 'can detail bom archive'), ('disable_bomarchive', 'can disable bom archive')),
            },
        ),
        migrations.CreateModel(
            name='QuotationArchive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_quotations', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationarchive_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotation_quotationarchive_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('quotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archived_quotations', to='quotation.Quotation', verbose_name='quotation')),
            ],
            options={
                'verbose_name_plural': 'quotation archives',
                'verbose_name': 'quotation archive',
                'permissions': (('list_quotationarchive', 'can list quotation archive'), ('detail_quotationarchive', 'can detail quotation archive'), ('disable_quotationarchive', 'can disable quotation archive')),
            },
        ),
    ]
