# -*- coding: utf-8 -*-

from django.conf.urls import url

from apps.quotation.api.frontend.views import user_views
from .views import tracker_views


user_urlpatterns = [
    url(
        r'^offer/detail/(?P<pk>\d+)/$',
        user_views.UserOfferDetailView.as_view(),
        name='tracker_offer_detail'
    ),
]

generic_urlpatterns = []

tracker_urlpatterns = [
    url(
        r'^bom/sender_list/$',
        tracker_views.TrackerBomSenderListView.as_view(),
        name='tracker_bom_sender_list'
    ),
    url(
        r'^bom/draft_list/$',
        tracker_views.TrackerBomDraftListView.as_view(),
        name='tracker_bom_draft_list'
    ),
    url(
        r'^bom/receiver_list/$',
        tracker_views.TrackerBomReceiverListView.as_view(),
        name='tracker_bom_receiver_list'
    ),
    url(
        r'^bom/(?P<pk>\d+)/$',
        tracker_views.TrackerBomDetailView.as_view(),
        name='tracker_bom_detail'
    ),
    url(
        r'^bom/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/$',
        tracker_views.TrackerBomBomTypeDetailView.as_view(),
        name='tracker_bom_detail'
    ),
    url(
        r'^bom/add/$',
        tracker_views.TrackerBomAddView.as_view(),
        name='tracker_bom_add'
    ),
    url(
        r'^bom/edit/(?P<pk>\d+)/$',
        tracker_views.TrackerBomEditView.as_view(),
        name='tracker_bom_edit'
    ),
    url(
        r'^bom/publish/(?P<pk>\d+)/$',
        tracker_views.TrackerBomPublishView.as_view(),
        name='tracker_bom_publish'
    ),
    url(
        r'^bom/send/(?P<pk>\d+)/$',
        tracker_views.TrackerBomSendView.as_view(),
        name='tracker_bom_send'
    ),
    url(
        r'^bom/delete/(?P<pk>\d+)/$',
        tracker_views.TrackerBomDeleteView.as_view(),
        name='tracker_bom_delete'
    ),
    url(
        r'^bom/(?P<pk>\d+)/row_add/$',
        tracker_views.TrackerBomBomRowAddView.as_view(),
        name='tracker_bom_bom_row_add'
    ),
    url(
        r'^bom/(?P<pk>\d+)/row_list/$',
        tracker_views.TrackerBomBomRowListView.as_view(),
        name='tracker_bom_bom_row_list'
    ),
    url(
        r'^bom/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/row_list/$',
        tracker_views.TrackerBomBomTypeBomRowListView.as_view(),
        name='tracker_bom_bom_row_list'
    ),
    url(
        r'^bom/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/document_list/$',
        tracker_views.TrackerBomBomTypeDocumentListView.as_view(),
        name='tracker_bom_bom_type_document_list'
    ),
    url(
        r'^bom/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/photo_list/$',
        tracker_views.TrackerBomBomTypePhotoListView.as_view(),
        name='tracker_bom_bom_type_photo_list'
    ),
    url(
        r'^bom/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/video_list/$',
        tracker_views.TrackerBomBomTypeVideoListView.as_view(),
        name='tracker_bom_bom_type_video_list'
    ),
    url(
        r'^bom_row/(?P<pk>\d+)/$',
        tracker_views.TrackerBomRowDetailView.as_view(),
        name='tracker_bom_row_detail'
    ),
    url(
        r'^bom_row/(?P<bom_type>(sent|received|draft){1})/(?P<pk>\d+)/$',
        tracker_views.TrackerBomRowBomTypeDetailView.as_view(),
        name='tracker_bom_row_detail'
    ),
    url(
        r'^bom_row/edit/(?P<pk>\d+)/$',
        tracker_views.TrackerBomRowEditView.as_view(),
        name='tracker_bom_row_edit'
    ),
    url(
        r'^bom_row/delete/(?P<pk>\d+)/$',
        tracker_views.TrackerBomRowDeleteView.as_view(),
        name='tracker_bom_row_delete'
    ),
    url(
        r'^bom_archive/add/$',
        tracker_views.TrackerBomArchiveAddView.as_view(),
        name='tracker_bom_archive_add'
    ),
    url(
        r'^quotation/sender_list/$',
        tracker_views.TrackerQuotationSenderListView.as_view(),
        name='tracker_quotation_sender_list'
    ),
    url(
        r'^quotation/draft_list/$',
        tracker_views.TrackerQuotationDraftListView.as_view(),
        name='tracker_quotation_draft_list'
    ),
    url(
        r'^quotation/receiver_list/$',
        tracker_views.TrackerQuotationReceiverListView.as_view(),
        name='tracker_quotation_receiver_list'
    ),
    url(
        r'^quotation/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationDetailView.as_view(),
        name='tracker_quotation_detail'
    ),
    url(
        r'^quotation/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationTypeDetailView.as_view(),
        name='tracker_quotation_type_detail'
    ),
    url(
        r'^bom/(?P<pk>\d+)/quotation_add/$',
        tracker_views.TrackerBomQuotationAddView.as_view(),
        name='tracker_bom_quotation_add'
    ),
    url(
        r'^quotation/edit/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationEditView.as_view(),
        name='tracker_quotation_edit'
    ),
    url(
        r'^quotation/(?P<type>(sent|received|draft){1})/accept/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationAcceptView.as_view(),
        name='tracker_quotation_accept'
    ),
    url(
        r'^quotation/delete/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationDeleteView.as_view(),
        name='tracker_quotation_delete'
    ),
    url(
        r'^quotation/(?P<pk>\d+)/row_list/$',
        tracker_views.TrackerQuotationQuotationRowListView.as_view(),
        name='tracker_quotation_quotation_row_list'
    ),
    url(
        r'^quotation/(?P<type>(sent|received|draft){1})/(?P<pk>\d+)/row_list/$',
        tracker_views.TrackerQuotationQuotationTypeQuotationRowListView.as_view(),
        name='tracker_quotation_quotation_type_quotation_row_list'
    ),
    url(
        r'^quotation_archive/add/$',
        tracker_views.TrackerQuotationArchiveAddView.as_view(),
        name='tracker_quotation_archive_add'
    ),
    url(
        r'^quotation_row/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationRowDetailView.as_view(),
        name='tracker_quotation_row_detail'
    ),
    url(
        r'^bom_row/(?P<bomrow_pk>\d+)/quotation/(?P<quotation_pk>\d+)/row_add/$',
        tracker_views.TrackerBomRowQuotationRowAddView.as_view(),
        name='tracker_bom_row_quotation_row_add'
    ),
    url(
        r'^quotation_row/edit/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationRowEditView.as_view(),
        name='tracker_quotation_row_edit'
    ),
    url(
        r'^quotation_row/delete/(?P<pk>\d+)/$',
        tracker_views.TrackerQuotationRowDeleteView.as_view(),
        name='tracker_quotation_row_delete'
    ),
    url(
        r'^offer/$',
        tracker_views.TrackerOfferListView.as_view(),
        name='tracker_offer_list'
    ),
    url(
        r'^offer/received_list/$',
        tracker_views.TrackerReceivedOffersListView.as_view(),
        name='tracker_received_offers_list'
    ),
    url(
        r'^offer/received_favourite_list/$',
        tracker_views.TrackerReceivedFavouriteOffersListView.as_view(),
        name='tracker_received_offers_list'
    ),
    url(
        r'^offer/received_required_list/$',
        tracker_views.TrackerReceivedRequiredOffersListView.as_view(),
        name='tracker_received_offers_list'
    ),
    url(
        r'^offer/sent_list/$',
        tracker_views.TrackerSentOffersListView.as_view(),
        name='tracker_received_offers_list'
    ),
    url(
        r'^offer/draft_list/$',
        tracker_views.TrackerDraftOffersListView.as_view(),
        name='tracker_draft_offers_list'
    ),
    url(
        r'^offer/(?P<pk>\d+)/$',
        tracker_views.TrackerOfferDetailView.as_view(),
        name='tracker_offer_detail'
    ),
    url(
        r'^offer/add/$',
        tracker_views.TrackerOfferAddView.as_view(),
        name='tracker_offer_add'
    ),
    url(
        r'^offer/edit/(?P<pk>\d+)/$',
        tracker_views.TrackerOfferEditView.as_view(),
        name='tracker_offer_edit'
    ),
    url(
        r'^offer/enable/(?P<pk>\d+)/$',
        tracker_views.TrackerOfferEnableView.as_view(),
        name='tracker_offer_enable'
    ),
    url(
        r'^offer/disable/(?P<pk>\d+)/$',
        tracker_views.TrackerOfferDisableView.as_view(),
        name='tracker_offer_disable'
    ),
    url(
        r'^offer/delete/(?P<pk>\d+)/$',
        tracker_views.TrackerOfferDeleteView.as_view(),
        name='tracker_offer_delete'
    ),
    url(
        r'^offer/follow/$',
        tracker_views.TrackerOfferFollowView.as_view(),
        name='tracker_offer_follow'
    ),
    url(
        r'^offer/(?P<offer_id>\d+)/unfollow/$',
        tracker_views.TrackerOfferUnFollowView.as_view(),
        name='tracker_offer_unfollow'
    ),
    url(
        r'^offer/buy/$',
        tracker_views.TrackerOfferBuyView.as_view(),
        name='tracker_offer_buy'
    ),
    url(
        r'^offer/(?P<offer_id>\d+)/cancel_buy/$',
        tracker_views.TrackerOfferCancelBuyView.as_view(),
        name='tracker_offer_cancel_buy'
    ),
    url(
        r'^certification/$',
        tracker_views.TrackerCertificationListView.as_view(),
        name='tracker_certification_list'
    ),
    url(
        r'^certification/(?P<pk>\d+)/$',
        tracker_views.TrackerCertificationDetailView.as_view(),
        name='tracker_certification_detail'
    ),
    url(
        r'^certification/add/$',
        tracker_views.TrackerCertificationAddView.as_view(),
        name='tracker_certification_add'
    ),
    url(
        r'^certification/edit/(?P<pk>\d+)/$',
        tracker_views.TrackerCertificationEditView.as_view(),
        name='tracker_certification_edit'
    ),
    url(
        r'^certification/enable/(?P<pk>\d+)/$',
        tracker_views.TrackerCertificationEnableView.as_view(),
        name='tracker_certification_enable'
    ),
    url(
        r'^certification/disable/(?P<pk>\d+)/$',
        tracker_views.TrackerCertificationDisableView.as_view(),
        name='tracker_certification_disable'
    ),
    url(
        r'^certification/delete/(?P<pk>\d+)/$',
        tracker_views.TrackerCertificationDeleteView.as_view(),
        name='tracker_certification_delete'
    ),
]

urlpatterns = user_urlpatterns + generic_urlpatterns + tracker_urlpatterns
