# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 20:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_auto_20170711_0719'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='members',
        ),
    ]
