# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_remove_company_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='company_invitation_refuse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='company invitation refuse date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_invitation_refuse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='profile invitation refuse date'),
        ),
    ]
