# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 10:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_auto_20170711_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('o', 'owner'), ('d', 'delegate'), ('m', 'level 1'), ('w', 'level 2')], max_length=1, null=True, verbose_name='role'),
        ),
    ]
