# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 15:53
from __future__ import unicode_literals

import apps.profile.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_auto_20170713_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=apps.profile.models.profile_info_default, help_text='More information about profile', null=True, verbose_name='info'),
        ),
    ]
