# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_auto_20170713_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profile_invitation_date',
        ),
    ]
