# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_remove_profile_profile_invitation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_invitation_refuse_date',
        ),
    ]
