# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 09:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_remove_profile_company_invitation_refuse_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='approval_date',
            new_name='profile_approval_date',
        ),
    ]
