# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-14 15:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0011_auto_20170714_0903'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='key')),
                ('company', models.ForeignKey(help_text='company', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_invitation_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_invitation_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to=settings.AUTH_USER_MODEL, verbose_name='inviter user')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
