# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-17 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0012_invitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='key',
        ),
    ]
