# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 15:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_remove_invitation_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='role',
        ),
        migrations.AddField(
            model_name='tracking',
            name='profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='profile.Profile', verbose_name='profile'),
            preserve_default=False,
        ),
    ]
