# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 09:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_auto_20170721_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracking',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trackings', to='profile.Profile', verbose_name='profiles'),
        ),
    ]
