# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-26 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_auto_20170724_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='last_modifier',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='user',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
