# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-27 14:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_auto_20170726_0831'),
    ]

    operations = [
        migrations.CreateModel(
            name='DelegateProfile',
            fields=[
            ],
            options={
                'permissions': (('list_delegateprofile', 'can list delegate profile'), ('detail_delegateprofile', 'can detail delegate profile'), ('disable_delegateprofile', 'can disable delegate profile')),
                'indexes': [],
                'verbose_name_plural': 'delegate profiles',
                'verbose_name': 'delegate profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
        migrations.CreateModel(
            name='GuestProfile',
            fields=[
            ],
            options={
                'permissions': (('list_guestprofile', 'can list guest profile'), ('detail_guestprofile', 'can detail guest profile'), ('disable_guestprofile', 'can disable guest profile')),
                'indexes': [],
                'verbose_name_plural': 'guest profiles',
                'verbose_name': 'guest profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
        migrations.CreateModel(
            name='Level1Profile',
            fields=[
            ],
            options={
                'permissions': (('list_level1profile', 'can list level 1 profile'), ('detail_level1profile', 'can detail level 1 profile'), ('disable_level1profile', 'can disable level 1 profile')),
                'indexes': [],
                'verbose_name_plural': 'level 1 profiles',
                'verbose_name': 'level 1 profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
        migrations.CreateModel(
            name='Level2Profile',
            fields=[
            ],
            options={
                'permissions': (('list_level2profile', 'can list level 2 profile'), ('detail_level2profile', 'can detail level 2 profile'), ('disable_level2profile', 'can disable level 2 profile')),
                'indexes': [],
                'verbose_name_plural': 'level 2 profiles',
                'verbose_name': 'level 2 profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
        migrations.CreateModel(
            name='MainProfile',
            fields=[
            ],
            options={
                'permissions': (('list_mainprofile', 'can list main profile'), ('detail_mainprofile', 'can detail main profile'), ('disable_mainprofile', 'can disable main profile')),
                'indexes': [],
                'verbose_name_plural': 'main profiles',
                'verbose_name': 'main profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
        migrations.CreateModel(
            name='OwnerProfile',
            fields=[
            ],
            options={
                'permissions': (('list_ownerprofile', 'can list owner profile'), ('detail_ownerprofile', 'can detail owner profile'), ('disable_ownerprofile', 'can disable owner profile')),
                'indexes': [],
                'verbose_name_plural': 'owner profiles',
                'verbose_name': 'owner profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
        migrations.CreateModel(
            name='PhantomProfile',
            fields=[
            ],
            options={
                'permissions': (('list_phantomprofile', 'can list phantom profile'), ('detail_phantomprofile', 'can detail phantom profile'), ('disable_phantomprofile', 'can disable phantom profile')),
                'indexes': [],
                'verbose_name_plural': 'phantom profiles',
                'verbose_name': 'phantom profile',
                'proxy': True,
            },
            bases=('profile.profile',),
        ),
    ]
