# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0017_delegateprofile_guestprofile_level1profile_level2profile_mainprofile_ownerprofile_phantomprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='company_invitation_date',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profile_approval_date',
        ),
        migrations.AddField(
            model_name='profile',
            name='company_invitation_send_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='company invitation send date'),
        ),
        migrations.AddField(
            model_name='profile',
            name='profile_invitation_approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='profile invitation approval date'),
        ),
    ]
