# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 13:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_auto_20170804_1557'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profile',
            unique_together=set([('company', 'email')]),
        ),
    ]
