# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-11 15:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0020_auto_20170906_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='token',
        ),
        migrations.AddField(
            model_name='tracking',
            name='user',
            field=models.OneToOneField(default=1, help_text='user', on_delete=django.db.models.deletion.CASCADE, related_name='tracking', to=settings.AUTH_USER_MODEL, verbose_name='user'),
            preserve_default=False,
        ),
    ]
