# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-14 15:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0021_auto_20170911_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracking',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='last_modifier',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='tracking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tracking',
        ),
    ]
