# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 10:17
from __future__ import unicode_literals

import apps.profile.models
from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0022_auto_20170914_1542'),
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('info', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default=apps.profile.models.profile_preference_info_default, help_text='More information about profile preference', null=True, verbose_name='info')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_preference_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_preference_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='profile.Profile', verbose_name='profile')),
            ],
            options={
                'verbose_name_plural': 'preferences',
                'verbose_name': 'preference',
                'permissions': (('list_preference', 'can list preference'), ('detail_preference', 'can detail preference'), ('disable_preference', 'can disable preference')),
            },
        ),
    ]
