# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0023_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preference', to='profile.Profile', verbose_name='profile'),
        ),
    ]
