# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-15 13:23
from __future__ import unicode_literals

import apps.profile.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0024_auto_20170915_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='info',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.profile.models.profile_preference_info_default, help_text='More information about profile preference', verbose_name='info'),
        ),
    ]
