# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0025_auto_20170915_1323'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='position'),
        ),
    ]
