# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 10:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0026_profile_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='company_invitation_send_date',
            new_name='company_invitation_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_invitation_refuse_date',
            new_name='invitation_refuse_date',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='profile_invitation_approval_date',
            new_name='profile_invitation_date',
        ),
    ]
