# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-05 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0027_auto_20171205_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company_invitation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='company invitation date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='invitation_refuse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation refuse date'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_invitation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='profile invitation date'),
        ),
    ]
