# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-14 08:50
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_auto_20171205_1001'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Company Categories', null=True, verbose_name='category'),
        ),
    ]
