# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-20 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0029_company_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
    ]
