# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-22 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0030_company_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_supplier',
            field=models.BooleanField(default=False, verbose_name='is supplier'),
        ),
    ]
