# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-03 14:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0032_profile_show_in_showroom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='show_in_showroom',
        ),
        migrations.AddField(
            model_name='profile',
            name='is_shared',
            field=models.BooleanField(default=False, verbose_name='is shared'),
        ),
    ]
