# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-18 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_auto_20180103_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnership',
            name='refuse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation refuse date'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation approval date'),
        ),
        migrations.AlterField(
            model_name='partnership',
            name='invitation_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='invitation request date'),
        ),
    ]
