# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0034_auto_20180118_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnership',
            name='guest_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_partnerships', to='profile.Company', verbose_name='request company'),
        ),
    ]
