# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-20 09:29
from __future__ import unicode_literals

import apps.profile.models
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0035_auto_20180119_0806'),
    ]

    operations = [
        migrations.AddField(
            model_name='preference',
            name='notification',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=apps.profile.models.profile_preference_notification_default, help_text='More information about profile notification', verbose_name='notification'),
        ),
    ]
