# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0036_preference_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_in_showroom',
            field=models.BooleanField(default=False, verbose_name='is in showroom'),
        ),
    ]
