# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-24 08:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0037_profile_is_in_showroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='favourite',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation approval date'),
        ),
        migrations.AddField(
            model_name='favourite',
            name='invitation_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2018, 1, 24, 8, 39, 9, 701119), verbose_name='invitation request date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='favourite',
            name='refuse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation refuse date'),
        ),
    ]
