# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_auto_20180124_0839'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'get_latest_by': 'date_create', 'ordering': ('ordering', 'name'), 'permissions': (('list_company', 'can list company'), ('detail_company', 'can detail company'), ('disable_company', 'can disable company')), 'verbose_name': 'company', 'verbose_name_plural': 'companies'},
        ),
        migrations.AlterModelOptions(
            name='favourite',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_create'], 'permissions': (('list_favourite', 'can list favourite'), ('detail_favourite', 'can detail favourite')), 'verbose_name': 'favourite', 'verbose_name_plural': 'favourites'},
        ),
        migrations.AlterModelOptions(
            name='partnership',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_create'], 'permissions': (('list_partnership', 'can list partnership'), ('detail_partnership', 'can detail partnership')), 'verbose_name': 'partnership', 'verbose_name_plural': 'partnerships'},
        ),
    ]
