# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 16:38
from __future__ import unicode_literals

from django.db import migrations


def empty_table(apps, schema_editor):
    favourites = apps.get_model('profile', 'Favourite')
    for fav in favourites.objects.all():
        fav.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0038_auto_20180124_0839'),
    ]

    operations = [
        migrations.RunPython(
            empty_table),
    ]
