# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 16:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0039_auto_20180129_1638'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='followers',
        ),
        migrations.AddField(
            model_name='favourite',
            name='company_followed',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='request_favourites', to='profile.Company', verbose_name='company followed'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='favourite',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='create_favourites', to='profile.Company', verbose_name='company'),
        ),
        migrations.AlterUniqueTogether(
            name='favourite',
            unique_together=set([('company_followed', 'company')]),
        ),
    ]
