# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-29 16:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0040_auto_20180129_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favourite',
            name='profile',
        ),
    ]
