# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0041_remove_favourite_profile'),
        ('profile', '0039_auto_20180130_0906'),
    ]

    operations = [
    ]
