# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-05-30 12:25
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0042_merge_20180130_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable'), (2, 'requested')], default=0, verbose_name='status')),
                ('short_description', models.CharField(max_length=50, verbose_name='short description')),
                ('tags', django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='Sponsor tags', null=True, verbose_name='tags')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sponsor', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sponsor_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_sponsor_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'verbose_name': 'sponsor',
                'verbose_name_plural': 'sponsors',
                'permissions': (('list_sponsor', 'can list sponsor'), ('detail_sponsor', 'can detail sponsor'), ('disable_sponsor', 'can disable sponsor')),
            },
        ),
        migrations.AddField(
            model_name='profile',
            name='is_superuser',
            field=models.BooleanField(default=False, verbose_name='is superuser'),
        ),
    ]
