# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-06-20 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0043_auto_20180530_1225'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='expired_date',
            field=models.DateField(blank=True, null=True, verbose_name='expired date'),
        ),
    ]
