# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-05 11:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0044_sponsor_expired_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='can_access_chat',
            field=models.BooleanField(default=True, verbose_name='can access chat'),
        ),
        migrations.AddField(
            model_name='profile',
            name='can_access_files',
            field=models.BooleanField(default=True, verbose_name='can access files'),
        ),
    ]
