# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-29 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0045_auto_20200705_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='project_invitation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='project invitation date'),
        ),
    ]
