# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-29 08:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0046_profile_project_invitation_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='project_invitation_date',
        ),
    ]
