# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-05 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0047_remove_profile_project_invitation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='color',
            field=models.CharField(blank=True, max_length=20, verbose_name='color'),
        ),
    ]
