# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-10-06 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_company_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_invited',
            field=models.BooleanField(default=False, verbose_name='is invited'),
        ),
    ]
