# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 15:36
from __future__ import unicode_literals

import apps.document.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_auto_20171204_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/home/vamsi/Projects/src/office2017.whistle.it'), upload_to=apps.document.models.get_upload_document_path, verbose_name='certification'),
        ),
    ]
