# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 15:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0004_auto_20180108_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is public'),
        ),
    ]
