# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 09:08
from __future__ import unicode_literals

import apps.document.models
import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0005_document_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/', location=settings.BASE_DIR), upload_to=apps.document.models.get_upload_document_path, verbose_name='certification'),
        ),
    ]
