# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0006_auto_20180117_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_last_modify'], 'permissions': (('list_document', 'can list document'), ('detail_document', 'can detail document'), ('disable_document', 'can disable document')), 'verbose_name': 'document', 'verbose_name_plural': 'documents'},
        ),
    ]
