# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 11:09
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('typology', models.CharField(choices=[('i', 'internal'), ('s', 'shared')], max_length=1, verbose_name='typology')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('description', models.TextField(verbose_name='description')),
                ('date_start', models.DateField(verbose_name='start date')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_project_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_project_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('referent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='referent_projects', to='profile.Profile', verbose_name='referent')),
                ('shared_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_projects', to='project.Project', verbose_name='internal project')),
            ],
            options={
                'verbose_name': 'project',
                'permissions': (('list_project', 'can list project'), ('detail_project', 'can detail project'), ('disable_project', 'can disable project')),
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('name', models.CharField(db_index=True, max_length=255, verbose_name='name')),
                ('date_start', models.DateField(verbose_name='start date')),
                ('date_end', models.DateField(verbose_name='end date')),
                ('date_completed', models.DateField(blank=True, null=True, verbose_name='completed date')),
                ('assigned_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='profile.Company', verbose_name='assigned company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_task_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='project.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'task',
                'permissions': (('list_task', 'can list task'), ('detail_task', 'can detail task'), ('disable_task', 'can disable task')),
                'verbose_name_plural': 'tasks',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('role', models.CharField(choices=[('o', 'owner'), ('d', 'delegate'), ('m', 'level 1'), ('w', 'level 2')], max_length=1, verbose_name='role')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_team_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='profile.Profile', verbose_name='contact')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='project.Project', verbose_name='project')),
            ],
            options={
                'verbose_name': 'team',
                'permissions': (('list_team', 'can list team'), ('detail_team', 'can detail team'), ('disable_team', 'can disable team')),
                'verbose_name_plural': 'teams',
            },
        ),
        migrations.AlterUniqueTogether(
            name='team',
            unique_together=set([('profile', 'project')]),
        ),
    ]
