# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status'),
        ),
    ]
