# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 11:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_profiles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='project.Project', verbose_name='project'),
        ),
    ]
