# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 15:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20170731_1151'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalProject',
            fields=[
            ],
            options={
                'proxy': True,
                'permissions': (('list_internalproject', 'can list internal project'), ('detail_internalproject', 'can detail internal project'), ('disable_internalproject', 'can disable internal project')),
                'indexes': [],
                'verbose_name': 'internal project',
                'verbose_name_plural': 'internal projects',
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='SharedProject',
            fields=[
            ],
            options={
                'proxy': True,
                'permissions': (('list_sharedproject', 'can list shared project'), ('detail_sharedproject', 'can detail shared project'), ('disable_sharedproject', 'can disable shared project')),
                'indexes': [],
                'verbose_name': 'shared project',
                'verbose_name_plural': 'shared projects',
            },
            bases=('project.project',),
        ),
    ]
