# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-31 20:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_internalproject_sharedproject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='shared_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_projects', to='project.Project', verbose_name='shared project'),
        ),
    ]
