# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-31 12:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_auto_20170731_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='shared_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='internal_tasks', to='project.Task', verbose_name='shared task'),
        ),
    ]
