# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 13:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0020_auto_20170906_1349'),
        ('project', '0008_task_shared_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('status', models.IntegerField(choices=[(0, 'start'), (1, 'finish')], default=1, verbose_name='status')),
                ('datetime_start', models.DateTimeField(verbose_name='start date time')),
                ('datetime_end', models.DateTimeField(verbose_name='end date time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_taskteam_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_taskteam_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_choices', to='profile.Profile', verbose_name='contact')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='todo_choices', to='project.Task', verbose_name='task')),
            ],
            options={
                'permissions': (('list_taskteam', 'can list task team'), ('detail_taskteam', 'can detail task team'), ('disable_taskteam', 'can disable task team')),
                'verbose_name': 'task team',
                'verbose_name_plural': 'task teams',
            },
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_workers',
            field=models.ManyToManyField(related_name='assigned_tasks', through='project.TaskTeam', to='profile.Profile', verbose_name='assigned workers'),
        ),
    ]
