# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-06 13:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20170906_1349'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskteam',
            name='status',
        ),
        migrations.AddField(
            model_name='taskteam',
            name='done',
            field=models.BooleanField(default=False, verbose_name='task complete'),
        ),
    ]
