# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-07 10:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0020_auto_20170906_1349'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0010_auto_20170906_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(db_index=True, max_length=255, verbose_name='title')),
                ('description', models.TextField(verbose_name='description')),
                ('done', models.BooleanField(default=False, verbose_name='task complete')),
                ('datetime_start', models.DateTimeField(verbose_name='start date time')),
                ('datetime_end', models.DateTimeField(verbose_name='end date time')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activity_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_activity_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profile.Profile', verbose_name='worker')),
            ],
            options={
                'permissions': (('list_activity', 'can list activity'), ('detail_activity', 'can detail activity'), ('disable_activity', 'can disable activity')),
                'verbose_name_plural': 'activities',
                'verbose_name': 'activity',
            },
        ),
        migrations.RemoveField(
            model_name='taskteam',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='taskteam',
            name='last_modifier',
        ),
        migrations.RemoveField(
            model_name='taskteam',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='taskteam',
            name='task',
        ),
        migrations.RemoveField(
            model_name='task',
            name='assigned_workers',
        ),
        migrations.DeleteModel(
            name='TaskTeam',
        ),
        migrations.AddField(
            model_name='activity',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='project.Task', verbose_name='task'),
        ),
        migrations.AddField(
            model_name='task',
            name='workers',
            field=models.ManyToManyField(related_name='tasks', through='project.Activity', to='profile.Profile', verbose_name='workers'),
        ),
    ]
