# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-26 12:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_auto_20170907_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='progress',
            field=models.IntegerField(default=0, verbose_name='progress percentage'),
        ),
    ]
