# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-03 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_task_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
