# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20171103_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='typology',
        ),
    ]
