# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-15 16:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_project_typology'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='note',
            field=models.TextField(blank=True, verbose_name='note'),
        ),
    ]
