# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-17 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_project_note'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenericProject',
            fields=[
            ],
            options={
                'verbose_name_plural': 'generic projects',
                'verbose_name': 'generic project',
                'indexes': [],
                'permissions': (('list_genericproject', 'can list generic project'), ('detail_genericproject', 'can detail generic project'), ('disable_genericproject', 'can disable generic project')),
                'proxy': True,
            },
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='InternalSharedProject',
            fields=[
            ],
            options={
                'verbose_name_plural': 'internal shared projects',
                'verbose_name': 'internal shared project',
                'indexes': [],
                'permissions': (('list_internalsharedproject', 'can list internal shared project'), ('detail_internalsharedproject', 'can detail internal shared project'), ('disable_internalsharedproject', 'can disable internal shared project')),
                'proxy': True,
            },
            bases=('project.project',),
        ),
    ]
