# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-18 10:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0028_auto_20171205_1001'),
        ('project', '0017_genericproject_internalsharedproject'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together=set([('company', 'name')]),
        ),
    ]
