# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0018_auto_20171218_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tags',
        ),
    ]
