# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-21 15:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_remove_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='tags',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, default={}, help_text='products', null=True, verbose_name='tags'),
        ),
    ]
