# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-16 15:52
from __future__ import unicode_literals

import apps.project.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0020_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='logo',
            field=models.ImageField(blank=True, upload_to=apps.project.models.get_upload_logo_path, verbose_name='logo'),
        ),
    ]
