# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-24 16:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_project_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='assigned_company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='profile.Company', verbose_name='assigned company'),
        ),
    ]
