# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-15 20:08
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0044_sponsor_expired_date'),
        ('project', '0023_auto_20180130_0906'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='project.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('photos', models.ImageField(blank=True, upload_to=apps.media.models.get_upload_photo_path, verbose_name='photos')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Profile')),
                ('sub_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Activity')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Post'),
        ),
    ]
