# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-23 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0027_auto_20200618_1728'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photos',
        ),
    ]
