# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-23 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0028_remove_post_photos'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='media',
            field=models.ImageField(blank=True, default='', upload_to='posts/'),
        ),
    ]
