# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-23 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0029_post_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, default='', upload_to='posts/'),
        ),
    ]
