# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-24 20:22
from __future__ import unicode_literals

import apps.project.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0030_auto_20200623_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskPostAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_taskpostassignment_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_taskpostassignment_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'ordering': ['-date_last_modify'],
                'get_latest_by': 'date_create',
                'verbose_name_plural': 'taskpostassignments',
                'permissions': (('list_task_post_assignment', 'can list task post assignment'), ('detail_task_post_assignment', 'can detail task post assignment'), ('disable_task_post_assignment', 'can disable task post assignment')),
                'verbose_name': 'task',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created_date', 'ordering': ['-created_date'], 'permissions': (('list_comment', 'can list comment'), ('detail_comment', 'can detail comment'), ('disable_comment', 'can disable comment')), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.AlterField(
            model_name='post',
            name='media',
            field=models.FileField(blank=True, default='', upload_to=apps.project.models.get_upload_post_path),
        ),
        migrations.AddField(
            model_name='taskpostassignment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Post'),
        ),
        migrations.AddField(
            model_name='taskpostassignment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Task'),
        ),
    ]
