# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-06-30 11:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0031_auto_20200624_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Task'),
        ),
        migrations.AlterField(
            model_name='post',
            name='sub_task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Activity'),
        ),
    ]
