# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-29 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0032_auto_20200630_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='project_invitation_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='project invitation date'),
        ),
    ]
