# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-29 09:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0033_team_project_invitation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='invitation_refuse_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='invitation refuse date'),
        ),
    ]
