# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-05 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_team_invitation_refuse_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericProject',
        ),
        migrations.DeleteModel(
            name='InternalProject',
        ),
        migrations.DeleteModel(
            name='InternalSharedProject',
        ),
        migrations.DeleteModel(
            name='SharedProject',
        ),
    ]
