# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-09 19:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0034_team_invitation_refuse_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericProject',
        ),
        migrations.DeleteModel(
            name='InternalProject',
        ),
        migrations.DeleteModel(
            name='InternalSharedProject',
        ),
        migrations.DeleteModel(
            name='SharedProject',
        ),
        migrations.AddField(
            model_name='activity',
            name='alert',
            field=models.BooleanField(default=False, verbose_name='alert'),
        ),
        migrations.AddField(
            model_name='activity',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='activity',
            name='starred',
            field=models.BooleanField(default=False, verbose_name='starred'),
        ),
        migrations.AddField(
            model_name='task',
            name='alert',
            field=models.BooleanField(default=False, verbose_name='alert'),
        ),
        migrations.AddField(
            model_name='task',
            name='note',
            field=models.TextField(blank=True, max_length=500, null=True, verbose_name='note'),
        ),
        migrations.AddField(
            model_name='task',
            name='starred',
            field=models.BooleanField(default=False, verbose_name='starred'),
        ),
    ]
