# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-10 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_company_color'),
        ('project', '0035_auto_20200809_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCompanyColorAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.Company')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.Project')),
            ],
        ),
    ]
