# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-11 10:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0036_projectcompanycolorassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime_end',
            field=models.DateField(verbose_name='end date'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='datetime_start',
            field=models.DateField(verbose_name='start date'),
        ),
    ]
