# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-08-31 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0038_auto_20200831_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='ordering',
            field=models.IntegerField(default=0, verbose_name='ordering'),
        ),
    ]
