# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-16 12:11
from __future__ import unicode_literals

import apps.project.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0039_comment_ordering'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaAssignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('media', models.FileField(blank=True, default='', upload_to=apps.project.models.get_upload_post_path)),
            ],
            options={
                'verbose_name_plural': 'image assignments',
                'verbose_name': 'image assignment',
            },
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'get_latest_by': 'created_date', 'ordering': ['created_date'], 'permissions': (('list_comment', 'can list comment'), ('detail_comment', 'can detail comment'), ('disable_comment', 'can disable comment')), 'verbose_name': 'comment', 'verbose_name_plural': 'comments'},
        ),
        migrations.RemoveField(
            model_name='post',
            name='media',
        ),
        migrations.AddField(
            model_name='mediaassignment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Comment'),
        ),
        migrations.AddField(
            model_name='mediaassignment',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Post'),
        ),
    ]
