# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-17 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0040_auto_20200916_1211'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaassignment',
            name='activity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Activity'),
        ),
        migrations.AddField(
            model_name='mediaassignment',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.Task'),
        ),
    ]
