# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-21 06:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0041_auto_20200917_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='alert',
            field=models.BooleanField(default=False, verbose_name='alert'),
        ),
    ]
