# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-21 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0048_company_color'),
        ('project', '0042_post_alert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='profile',
        ),
        migrations.RemoveField(
            model_name='task',
            name='workers',
        ),
        migrations.AddField(
            model_name='activity',
            name='workers',
            field=models.ManyToManyField(related_name='activities', to='profile.Profile', verbose_name='workers'),
        ),
    ]
