# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-09-24 22:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0043_auto_20200921_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'get_latest_by': 'date_create', 'ordering': ['date_create'], 'permissions': (('list_activity', 'can list activity'), ('detail_activity', 'can detail activity'), ('disable_activity', 'can disable activity')), 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
    ]
