# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 08:35
from __future__ import unicode_literals

import apps.media.models
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='publication date')),
                ('photo', models.ImageField(upload_to=apps.media.models.get_upload_photo_path, verbose_name='image')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_photo_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_photo_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'verbose_name': 'photo',
                'verbose_name_plural': 'photos',
                'permissions': (('list_photo', 'can list photo'), ('detail_photo', 'can detail photo'), ('disable_photo', 'can disable photo')),
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('status', models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, null=True, verbose_name='status')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('pub_date', models.DateField(blank=True, verbose_name='publication date')),
                ('video', models.FileField(upload_to=apps.media.models.get_upload_video_path, verbose_name='video')),
                ('note', models.TextField(blank=True, verbose_name='note')),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, size=None)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='profile.Company', verbose_name='company')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_video_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_video_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'verbose_name': 'video',
                'verbose_name_plural': 'videos',
                'permissions': (('list_video', 'can list video'), ('detail_video', 'can detail video'), ('disable_video', 'can disable video')),
            },
        ),
    ]
