# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 13:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20170713_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), blank=True, null=True, size=None),
        ),
    ]
