# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0004_auto_20170720_1406'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='pub_date',
            field=models.DateField(blank=True, null=True, verbose_name='publication date'),
        ),
    ]
