# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 14:48
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('media', '0005_auto_20170720_1407'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='company',
        ),
        migrations.RemoveField(
            model_name='video',
            name='company',
        ),
        migrations.AddField(
            model_name='photo',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='photo',
            name='for_concrete_model',
            field=models.BooleanField(default=False, verbose_name='for concrete model'),
        ),
        migrations.AddField(
            model_name='photo',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='for_concrete_model',
            field=models.BooleanField(default=False, verbose_name='for concrete model'),
        ),
        migrations.AddField(
            model_name='video',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.ImageField(upload_to=apps.media.models.get_upload_video_path, verbose_name='video'),
        ),
    ]
