# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-29 16:11
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0006_auto_20170722_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=apps.media.models.get_upload_video_path, verbose_name='video'),
        ),
    ]
