# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-04 09:22
from __future__ import unicode_literals

import apps.media.models
import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0007_auto_20171129_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location=settings.UPLOAD_FILE_PATH), upload_to=apps.media.models.get_upload_photo_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location=settings.UPLOAD_FILE_PATH), upload_to=apps.media.models.get_upload_video_path, verbose_name='video'),
        ),
    ]
