# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 09:39
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0008_auto_20171204_0922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=apps.media.models.get_upload_photo_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(upload_to=apps.media.models.get_upload_video_path, verbose_name='video'),
        ),
    ]
