# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0010_photo_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='is public'),
        ),
    ]
