# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0011_video_is_public'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to='', verbose_name='image'),
        ),
    ]
