# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-08 12:01
from __future__ import unicode_literals

import apps.media.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0012_auto_20180108_1143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(upload_to=apps.media.models.get_upload_photo_path, verbose_name='image'),
        ),
    ]
