# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-17 09:08
from __future__ import unicode_literals

import apps.media.models
import django.core.files.storage
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0015_auto_20180108_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(base_url='/', location=settings.BASE_DIR), upload_to=apps.media.models.get_upload_photo_path, verbose_name='image'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/', location=settings.BASE_DIR), upload_to=apps.media.models.get_upload_video_path, verbose_name='video'),
        ),
    ]
