# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0016_auto_20180117_0908'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_last_modify'], 'permissions': (('list_photo', 'can list photo'), ('detail_photo', 'can detail photo'), ('disable_photo', 'can disable photo')), 'verbose_name': 'photo', 'verbose_name_plural': 'photos'},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_last_modify'], 'permissions': (('list_video', 'can list video'), ('detail_video', 'can detail video'), ('disable_video', 'can disable video')), 'verbose_name': 'video', 'verbose_name_plural': 'videos'},
        ),
    ]
