# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-20 09:56
from __future__ import unicode_literals

import apps.media.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0017_auto_20180130_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='photo',
            field=models.ImageField(max_length=1000, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/opt/project'), upload_to=apps.media.models.get_upload_photo_path, verbose_name='image'),
        ),
    ]
