# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-07-25 17:35
from __future__ import unicode_literals

import apps.media.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0018_auto_20200720_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(max_length=1000, storage=django.core.files.storage.FileSystemStorage(base_url='/', location='/opt/project'), upload_to=apps.media.models.get_upload_video_path, verbose_name='video'),
        ),
    ]
