# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 15:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profile', '0001_initial'),
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='profile.Profile', verbose_name='sender'),
        ),
        migrations.AddField(
            model_name='message',
            name='talk',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='message.Talk', verbose_name='talk'),
        ),
    ]
