# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('message', '0002_auto_20170710_1525'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='object_id',
            new_name='talk_object_id',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='content_type',
        ),
        migrations.AddField(
            model_name='talk',
            name='talk_content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='talks', to='contenttypes.ContentType'),
            preserve_default=False,
        ),
    ]
