# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 08:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_auto_20170711_1330'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='talk_content_type',
            new_name='content_type',
        ),
        migrations.RenameField(
            model_name='talk',
            old_name='talk_object_id',
            new_name='object_id',
        ),
    ]
