# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-13 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_auto_20170712_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='talk',
            name='status',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status'),
        ),
    ]
