# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-22 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0019_auto_20170804_1557'),
        ('message', '0005_auto_20170713_1303'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='receiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='receive_messages', to='profile.Profile', verbose_name='receiver'),
            preserve_default=False,
        ),
    ]
