# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-08 08:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0006_message_receiver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver',
        ),
    ]
