# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0007_remove_message_receiver'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_last_modify'], 'permissions': (('list_message', 'can list message'), ('detail_message', 'can detail message'), ('disable_message', 'can disable message')), 'verbose_name': 'message', 'verbose_name_plural': 'messages'},
        ),
        migrations.AlterModelOptions(
            name='talk',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_last_modify'], 'permissions': (('list_talk', 'can list talk'), ('detail_talk', 'can detail talk'), ('disable_talk', 'can disable talk')), 'verbose_name': 'talk', 'verbose_name_plural': 'talks'},
        ),
    ]
