# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2020-10-01 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0010_messagefileassignment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='body',
            field=models.TextField(blank=True, verbose_name='body'),
        ),
    ]
