# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 10:05
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('profile', '0033_auto_20180103_1426'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationRecipient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('is_email', models.BooleanField(default=False, verbose_name='is email')),
                ('is_notify', models.BooleanField(default=False, verbose_name='is notify')),
                ('reading_date', models.DateTimeField(blank=True, null=True, verbose_name='reading date')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_notificationrecipient_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_notificationrecipient_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
            ],
            options={
                'verbose_name_plural': 'notification recipients',
                'verbose_name': 'notification recipient',
                'permissions': (('list_notificationrecipient', 'can list notification recipient'), ('detail_notificationrecipient', 'can detail notification recipient'), ('disable_notificationrecipient', 'can disable notification recipient')),
            },
        ),
        migrations.CreateModel(
            name='Notify',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateTimeField(auto_now_add=True, verbose_name='date create')),
                ('date_last_modify', models.DateTimeField(auto_now=True, verbose_name='date last modify')),
                ('ordering', models.IntegerField(default=0, verbose_name='ordering')),
                ('event', models.CharField(choices=[('mr', 'received message')], max_length=3, verbose_name='event')),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='contenttypes.ContentType')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_notify_creator', to=settings.AUTH_USER_MODEL, verbose_name='creator')),
                ('last_modifier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notify_notify_last_modifier', to=settings.AUTH_USER_MODEL, verbose_name='last modifier')),
                ('recipients', models.ManyToManyField(related_name='recipients', through='notify.NotificationRecipient', to='profile.Profile', verbose_name='recipients')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_sender', to='profile.Profile', verbose_name='sender')),
            ],
            options={
                'verbose_name_plural': 'notifies',
                'verbose_name': 'notify',
                'permissions': (('list_notify', 'can list notify'), ('detail_notify', 'can detail notify'), ('disable_notify', 'can disable notify')),
            },
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='notify',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to='notify.Notify', verbose_name='notify'),
        ),
        migrations.AddField(
            model_name='notificationrecipient',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to='profile.Profile', verbose_name='recipient'),
        ),
    ]
