# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 11:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20180109_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notificationrecipient',
            old_name='notify',
            new_name='notification',
        ),
    ]
