# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 11:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20180109_1112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationrecipient',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_recipient', to='notify.Notify', verbose_name='notification'),
        ),
    ]
