# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-09 11:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0033_auto_20180103_1426'),
        ('notify', '0004_auto_20180109_1113'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='notificationrecipient',
            unique_together=set([('recipient', 'notification')]),
        ),
    ]
