# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-10 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20180109_1119'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='status',
            field=models.IntegerField(choices=[(0, 'disable'), (1, 'enable')], default=1, verbose_name='status'),
        ),
    ]
