# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-19 14:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0006_notificationrecipient_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationrecipient',
            name='is_email_sent',
            field=models.BooleanField(default=False, verbose_name='is email sent'),
        ),
    ]
