# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-23 10:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0007_notificationrecipient_is_email_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notify',
            name='event',
        ),
    ]
