# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-30 09:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0008_remove_notify_event'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notificationrecipient',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_create'], 'permissions': (('list_notificationrecipient', 'can list notification recipient'), ('detail_notificationrecipient', 'can detail notification recipient'), ('disable_notificationrecipient', 'can disable notification recipient')), 'verbose_name': 'notification recipient', 'verbose_name_plural': 'notification recipients'},
        ),
        migrations.AlterModelOptions(
            name='notify',
            options={'get_latest_by': 'date_create', 'ordering': ['-date_create'], 'permissions': (('list_notify', 'can list notify'), ('detail_notify', 'can detail notify'), ('disable_notify', 'can disable notify')), 'verbose_name': 'notify', 'verbose_name_plural': 'notifies'},
        ),
    ]
